var ironMap = {isDust:true, isPlate:true, isNugget:true, isSmallDust:true, isTinyDust:true, isBolt:true, isRods:true, isCrushed: true, isCrushedPurified: true, isSawBlade: true, isMagneticRod: true, generateRecipes:true};
var steel_bronzeMap = {isBlock: true, isIngot: true, isDust:true, isPlate:true, isNugget:true, isSmallDust:true, isTinyDust:true, isBolt:true, isRods:true, isScrew: true, isSawBlade: true, isGearSmall: true, generateRecipes:true};
var rubberMap = {isIngot: true, isDust:true, isPlate:true, isNugget:true, isSmallDust:true, isTinyDust:true, isBolt:true,  isRods:true, isRing: true, generateRecipes: true};
var copperMap = {isBlock: true, isIngot: true, isDust:true, isPlate:true, isNugget:true, isSmallDust:true, isTinyDust:true, isBolt:true, isRods:true, isCrushed: true, isCrushedPurified: true, isScrew: true, generateRecipes:true};
var wroughtMap = {isIngot: true, isDust:true, isPlate:true, isNugget:true, isSmallDust:true, isTinyDust:true, isBolt:true, isRods:true, generateRecipes:true};
var leadMap = {isIngot: true, isDust:true, isPlate:true, isNugget:true, isSmallDust:true, isTinyDust:true, isBolt:true, isRods:true, isCrushed: true, isCrushedPurified: true, isScrew: true, generateRecipes:true};
var ch_al_ti_st_wMap = {isIngot: true, isDust: true, isPlate: true, isNugget: true, isScrew: true, isSmallDust: true, generateRecipes:true};
var ashesMap = {isDust: true, isTinyDust: true, generateRecipes: true};
var crushedMap = {isCrushed: true, generateRecipes: false};
var coal_ligniteMap = {isDust: true, isCrushed: true, isCrushedPurified: true, generateRecipes: true};
var diamond_emeraldMap = {isDust: true, isPlate: true, isSmallDust: true, isTinyDust: true, isCrushed: true, isCrushedPurified: true, generateRecipes: true};
var redstoneMap = {isPlate: true, isCrushed: true, isCrushedPurified: true, generateRecipes: false};
var stones = {isDust:true, isSmallDust:true, generateRecipes:true};
var antimonyMap = {isIngot: true, isDust: true, isNugget: true, isPlate: true, isRods: true, isSmallDust: true, isTinyDust: true, isBolt: true, generateRecipes: true};
var silverMap = {isIngot: true, isDust: true, isNugget: true, isPlate: true, isRods: true, isSmallDust: true, isTinyDust: true, isBolt: true, isCrushed: true, isCrushedPurified: true, isSawBlade: true, isBlock: true, generateRecipes: true};
var tinMap = {isIngot: true, isDust: true, isNugget: true, isPlate: true, isRods: true, isSmallDust: true, isTinyDust: true, isBolt: true, isScrew: true, isRing: true, isCrushed: true, isCrushedPurified: true, isBlock: true, generateRecipes: true};
var goldMap = {isDust: true, isNugget: true, isPlate: true, isRods: true, isSmallDust: true, isTinyDust: true, isBolt: true, isScrew: true, isCrushed: true, isCrushedPurified: true, isSawBlade: true, generateRecipes: true};
var bauxiteMap = {isDust:true, isSmallDust:true, generateRecipes:true};
var nickelMap = {isDust:true, isIngot:true, isPlate:true, isNugget:true, isSmallDust:true, generateRecipes:true};

GT_Material.register("Iron", ironMap, {temp: 1600, long: 40, lvl: 2});
GT_Material.register("Steel", steel_bronzeMap, {temp: 1600, long: 240, lvl: 2});
GT_Material.register("Rubber", rubberMap, {temp: 200, long: 10, lvl: 2});
GT_Material.register("Copper", copperMap, {temp: 1000, long: 100, lvl: 2});
GT_Material.register("WroughtIron", wroughtMap, {temp: 1600, long: 40, lvl: 2});
GT_Material.register("Lead", leadMap, {temp: 300, long: 10, lvl: 2});
GT_Material.register("Gold", goldMap, {temp: 1000, long: 10, lvl: 1});
GT_Material.register("Tin", tinMap, {temp: 200, long: 10, lvl: 1});
GT_Material.register("Silver", silverMap, {temp: 900, long: 10, lvl: 1});
GT_Material.register("Bronze", steel_bronzeMap, {temp: 1000, long: 100, lvl: 2});
GT_Material.register("Antimony", antimonyMap, {temp: 1600, long: 40, lvl: 2});
GT_Material.register("LapisLazuli", {isDust: true, isPlate: true, isCrushed: true, isCrushedPurified: true, generateRecipes:true}, {temp: 600, long: 10, lvl: 1});
GT_Material.register("Redstone", redstoneMap, {temp: 200, long: 40, lvl: 2});
GT_Material.register("Diamond", diamond_emeraldMap, {temp: 4000, long: 400, lvl: 3});
GT_Material.register("Emerald", diamond_emeraldMap, {temp: 1400, long: 400, lvl: 3});
GT_Material.register("Lignite", coal_ligniteMap, {temp: 200, long: 10, lvl: 1});
GT_Material.register("Coal", coal_ligniteMap, {temp: 200, long: 10, lvl: 1});
GT_Material.register("Cassiterite", crushedMap, {temp: 1600, long: 40, lvl: 2});
GT_Material.register("BrownLimonite", crushedMap, {temp: 1600, long: 40, lvl: 2});
GT_Material.register("YellowLimonite", crushedMap, {temp: 1600, long: 40, lvl: 2});
GT_Material.register("BandedIron", crushedMap, {temp: 1600, long: 40, lvl: 2});
GT_Material.register("Malachite", crushedMap, {temp: 1600, long: 40, lvl: 2});
GT_Material.register("VanadiumMagnetite", crushedMap, {temp: 1600, long: 40, lvl: 2});
GT_Material.register("Magnetite", crushedMap, {temp: 1600, long: 40, lvl: 2});
GT_Material.register("Chalcopyrite", crushedMap, {temp: 1600, long: 40, lvl: 2});
GT_Material.register("Pyrite", crushedMap, {temp: 1600, long: 40, lvl: 2});
GT_Material.register("Tetrahedrite", crushedMap, {temp: 1600, long: 40, lvl: 2});
GT_Material.register("Galena", crushedMap, {temp: 1600, long: 40, lvl: 2});
GT_Material.register("Ashes", ashesMap, {temp: 200, long: 10, lvl: 1});
GT_Material.register("DarkAshes", ashesMap, {temp: 200, long: 10, lvl: 1});
GT_Material.register("Glass", {isDust: true, generateRecipes: true}, {temp: 200, long: 10, lvl: 1});
GT_Material.register("Wood", {isDust: true, isPlate: true, generateRecipes: false}, {temp: 200, long: 10, lvl: 1});
GT_Material.register("RedAlloy", {isIngot: true, isPlate: true, generateRecipes: true}, {temp: 200, long: 10, lvl: 1});

GT_Material.register("Sulfur", {isDust: true, isSmallDust: true, generateRecipes: true}, {temp: 200, long: 10, lvl: 1});
GT_Material.register("Chrome", ch_al_ti_st_wMap, {temp: 1900, long: 300, lvl: 3});
GT_Material.register("Aluminium", ch_al_ti_st_wMap, {temp: 600, long: 10, lvl: 2});
GT_Material.register("Titanium", ch_al_ti_st_wMap, {temp: 1600, long: 240, lvl: 3});
GT_Material.register("Stainless", ch_al_ti_st_wMap, {temp: 1800, long: 260, lvl: 3});
GT_Material.register("Wolfram", ch_al_ti_st_wMap, {temp: 3400, long: 400, lvl: 4});
GT_Material.register("Nickel", nickelMap, {temp:1400, long:60, lvl:1});

GT_Material.register("Stone", stones, {lvl: 2});
GT_Material.register("RedGranit", stones, {lvl: 2});
GT_Material.register("BlackGranit", stones, {lvl: 3});

GT_Material.register("Bauxite", bauxiteMap, {lvl:1});
GT_Material.register("Magnetite", {isDust:true, isSmallDust:true, generateRecipes:true}, {temp:1200, lvl:2, long:10});
GT_Material.register("Tetrahedrite", {isDust:true, isSmallDust:true, generateRecipes:true}, {temp: 1000, long: 10, lvl:1});
GT_Material.register("Galena", {isDust:true, isSmallDust:true, generateRecipes:true}, {temp: 800, long: 10, lvl:1});

GT_Material.RegisterImpureDust(ItemID.dustBauxite, [[ItemID.dustAluminium, 1], [ItemID.dustSmallTitanium, 4], [ItemID.dustSmallIron, 4]], GT_Material.RetArg("dusts", "Bauxite", "lvl"));
GT_Material.RegisterImpureDust(ItemID.dustRuby, [ItemID.dustChrome, 1, ItemID.dustAluminium, 1], GT_Material.RetArg("dusts", "Ruby", "lvl"));
GT_Material.RegisterImpureDust(331, [ItemID.dustSmallRuby, 1, ItemID.dustNikel, 1, ItemID.dustSmallBauxite, 1], GT_Material.RetArg("dusts", "Redstone", "lvl"));
GT_Material.RegisterImpureDust(ItemID.dustLapis, [ItemID.dustSmallSaphire, 1, ItemID.dustAluminium, 1, ItemID.dustSmallManganese, 2], GT_Material.RetArg("dusts", "Lapis", "lvl"));
GT_Material.RegisterImpureDust(ItemID.dustEmerald, [ItemID.dustSmallRuby, 1, ItemID.dustNikel, 1], GT_Material.RetArg("dusts", "Emerald", "lvl"));
GT_Material.RegisterImpureDust(ItemID.dustStainless, [ItemID.dustSmallIron, 3, ItemID.dustSmallNikel, 3, ItemID.dustSmallManganese, 2], GT_Material.RetArg("dusts", "Stainless", "lvl"));
GT_Material.RegisterImpureDust(ItemID.dustMagnetite, [ItemID.dustSmallIron, 4, ItemID.dustSmallGold, 4, ItemID.dustSmallVolfram, 1], GT_Material.RetArg("dusts", "Magnetite", "lvl"), true);
GT_Material.RegisterImpureDust(ItemID.dustRedGranit, [ItemID.dustSmallBauxite, 2, ItemID.dustSmallStone, 7], GT_Material.RetArg("dusts", "RedGranit", "lvl"));
GT_Material.RegisterImpureDust(ItemID.dustBlackGranit, [ItemID.dustSmallMagnetite, 2, ItemID.dustSmallStone, 7], GT_Material.RetArg("dusts", "BlackGranit", "lvl"));
GT_Material.RegisterImpureDust(ItemID.dustTetrahedrite, [ItemID.dustCopper, 1, ItemID.dustSmallChrome, 1], GT_Material.RetArg("dusts", "Tetrahedrite", "lvl"), true);
GT_Material.RegisterImpureDust(ItemID.dustGalena, [ItemID.dustSilver, 1, ItemID.dustLead, 1], GT_Material.RetArg("dusts", "Galena", "lvl"), true);
GT_Material.RegisterImpureDust(ItemID.dustMalachite, [ItemID.dustCopper, 1, ItemID.dustSmallEmerald, 1], GT_Material.RetArg("dusts", "Malachite", "lvl"), true);